export const products = [
  {
    title: "Women Evening Gown",
    category: "Ethnic Wear",
    color: "Brown",
    size: "S",
    price: 998,
    originalPrice: 1266,
    tag: "Limited Edition",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-long-casual-maxi-dress_53876-834127.jpg",
  },
  {
    title: "Women A-Line Dress",
    category: "Casual Wear",
    color: "Teal",
    size: "S",
    price: 1059,
    originalPrice: 1290,
    tag: "Popular",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-fashion-dress-gown-elegance_53876-727378.jpg",
  },
  {
    title: "Women Palazzo Set",
    category: "Loungewear",
    color: "Grey",
    size: "L",
    price: 962,
    originalPrice: 1254,
    tag: "Trending",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-floral-blue-summer-dress_53876-831765.jpg",
  },
  {
    title: "Women Anarkali Ethnic Wear",
    category: "Casual Wear",
    color: "Pink",
    size: "XS",
    price: 1138,
    originalPrice: 1486,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-yellow-ruffled-dress_53876-829486.jpg",
  },
  {
    title: "Women Floral Dress",
    category: "Party Wear",
    color: "Green",
    size: "XS",
    price: 1073,
    originalPrice: 1368,
    tag: "Trending",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-floral-blue-summer-dress_53876-831765.jpg",
  },
  {
    title: "Women Floral Dress",
    category: "By Length",
    color: "Grey",
    size: "M",
    price: 1188,
    originalPrice: 1506,
    tag: "Popular",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-yellow-ruffled-dress_53876-829486.jpg",
  },
  {
    title: "Women Floral Dress",
    category: "By Length",
    color: "Black",
    size: "XL",
    price: 1206,
    originalPrice: 1409,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-green-wrap-dress_53876-828927.jpg",
  },
  {
    title: "Women Printed Dress",
    category: "Casual Wear",
    color: "Purple",
    size: "XL",
    price: 1237,
    originalPrice: 1594,
    tag: "Trending",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-floral-blue-summer-dress_53876-831765.jpg",
  },
  {
    title: "Women Evening Gown",
    category: "Formal Wear",
    color: "Pink",
    size: "S",
    price: 1165,
    originalPrice: 1386,
    tag: "Best Seller",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-floral-blue-summer-dress_53876-831765.jpg",
  },
  {
    title: "Women Printed Dress",
    category: "Fusion Wear",
    color: "Green",
    size: "L",
    price: 1279,
    originalPrice: 1653,
    tag: "Limited Edition",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-fashion-dress-gown-elegance_53876-727378.jpg",
  },
  {
    title: "Women Printed Dress",
    category: "Active Wear",
    color: "Green",
    size: "S",
    price: 1372,
    originalPrice: 1735,
    tag: "Popular",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-fashion-dress-gown-elegance_53876-727378.jpg",
  },
  {
    title: "Women Anarkali Ethnic Wear",
    category: "Formal Wear",
    color: "Purple",
    size: "M",
    price: 1123,
    originalPrice: 1518,
    tag: "Best Seller",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-long-casual-maxi-dress_53876-834127.jpg",
  },
  {
    title: "Women Linen Dress",
    category: "Casual Wear",
    color: "Purple",
    size: "S",
    price: 1289,
    originalPrice: 1668,
    tag: "Trending",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-green-wrap-dress_53876-828927.jpg",
  },
  {
    title: "Women Maxi Dress",
    category: "Active Wear",
    color: "Red",
    size: "S",
    price: 1150,
    originalPrice: 1523,
    tag: "Trending",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-green-striped-summer-dress_53876-829122.jpg",
  },
  {
    title: "Women Kurti Set",
    category: "Western Wear",
    color: "Pink",
    size: "XS",
    price: 1421,
    originalPrice: 1733,
    tag: "Popular",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-green-striped-summer-dress_53876-829122.jpg",
  },
  {
    title: "Women Tunic Top",
    category: "Western Wear",
    color: "Teal",
    size: "XL",
    price: 1352,
    originalPrice: 1625,
    tag: "Popular",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-long-casual-maxi-dress_53876-834127.jpg",
  },
  {
    title: "Women A-Line Dress",
    category: "Party Wear",
    color: "Red",
    size: "XS",
    price: 926,
    originalPrice: 1288,
    tag: "Trending",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-long-casual-maxi-dress_53876-834127.jpg",
  },
  {
    title: "Women Kurti Set",
    category: "Fusion Wear",
    color: "White",
    size: "M",
    price: 958,
    originalPrice: 1345,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-long-casual-maxi-dress_53876-834127.jpg",
  },
  {
    title: "Women Printed Dress",
    category: "Casual Wear",
    color: "White",
    size: "XXL",
    price: 1250,
    originalPrice: 1488,
    tag: "Best Seller",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-green-wrap-dress_53876-828927.jpg",
  },
  {
    title: "Women Printed Dress",
    category: "Ethnic Wear",
    color: "Blue",
    size: "L",
    price: 950,
    originalPrice: 1236,
    tag: "Trending",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-long-casual-maxi-dress_53876-834127.jpg",
  },
  {
    title: "Women Floral Dress",
    category: "Occasion Wear",
    color: "Yellow",
    size: "XS",
    price: 1306,
    originalPrice: 1660,
    tag: "Popular",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-floral-blue-summer-dress_53876-831765.jpg",
  },
  {
    title: "Women Kurti Set",
    category: "Western Wear",
    color: "Pink",
    size: "M",
    price: 1259,
    originalPrice: 1520,
    tag: "Best Seller",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-floral-blue-summer-dress_53876-831765.jpg",
  },
  {
    title: "Women Maxi Dress",
    category: "By Length",
    color: "Red",
    size: "S",
    price: 1307,
    originalPrice: 1528,
    tag: "Best Seller",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-green-wrap-dress_53876-828927.jpg",
  },
  {
    title: "Women Cotton Midi Dress",
    category: "Loungewear",
    color: "Black",
    size: "XS",
    price: 1441,
    originalPrice: 1699,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-womens-minimal-long-dress-mockup_53876-1046092.jpg?uid=R155413258&ga=GA1.1.471318040.1721215360&semt=ais_items_boosted&w=740",
  },
  {
    title: "Women Bodycon Dress",
    category: "By Length",
    color: "Grey",
    size: "S",
    price: 1185,
    originalPrice: 1520,
    tag: "Popular",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-long-casual-maxi-dress_53876-834127.jpg",
  },
  {
    title: "Women Linen Dress",
    category: "Formal Wear",
    color: "Red",
    size: "S",
    price: 1365,
    originalPrice: 1701,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-yellow-ruffled-dress_53876-829486.jpg",
  },
  {
    title: "Women Bodycon Dress",
    category: "Fusion Wear",
    color: "Red",
    size: "L",
    price: 1238,
    originalPrice: 1608,
    tag: "Limited Edition",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-long-casual-maxi-dress_53876-834127.jpg",
  },
  {
    title: "Women Kurti Set",
    category: "Loungewear",
    color: "Green",
    size: "XXL",
    price: 1164,
    originalPrice: 1449,
    tag: "Popular",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-womens-minimal-long-dress-mockup_53876-1046092.jpg?uid=R155413258&ga=GA1.1.471318040.1721215360&semt=ais_items_boosted&w=740",
  },
  {
    title: "Women Evening Gown",
    category: "Ethnic Wear",
    color: "Teal",
    size: "XS",
    price: 1381,
    originalPrice: 1753,
    tag: "Best Seller",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-green-wrap-dress_53876-828927.jpg",
  },
  {
    title: "Women Linen Dress",
    category: "Ethnic Wear",
    color: "Green",
    size: "M",
    price: 1343,
    originalPrice: 1725,
    tag: "Trending",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-floral-blue-summer-dress_53876-831765.jpg",
  },
  {
    title: "Women Tunic Top",
    category: "Active Wear",
    color: "Pink",
    size: "XL",
    price: 1433,
    originalPrice: 1692,
    tag: "Popular",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-floral-blue-summer-dress_53876-831765.jpg",
  },
  {
    title: "Women Kurti Set",
    category: "Formal Wear",
    color: "Grey",
    size: "XL",
    price: 1419,
    originalPrice: 1636,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-green-wrap-dress_53876-828927.jpg",
  },
  {
    title: "Women Bodycon Dress",
    category: "Loungewear",
    color: "Teal",
    size: "XL",
    price: 1140,
    originalPrice: 1447,
    tag: "Popular",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-floral-blue-summer-dress_53876-831765.jpg",
  },
  {
    title: "Women Anarkali Ethnic Wear",
    category: "Occasion Wear",
    color: "Blue",
    size: "XS",
    price: 1359,
    originalPrice: 1657,
    tag: "Best Seller",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-floral-blue-summer-dress_53876-831765.jpg",
  },
  {
    title: "Women Cotton Midi Dress",
    category: "Formal Wear",
    color: "Black",
    size: "XS",
    price: 1115,
    originalPrice: 1446,
    tag: "Trending",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-yellow-ruffled-dress_53876-829486.jpg",
  },
  {
    title: "Women Kurti Set",
    category: "By Length",
    color: "White",
    size: "XS",
    price: 1320,
    originalPrice: 1628,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-yellow-ruffled-dress_53876-829486.jpg",
  },
  {
    title: "Women Maxi Dress",
    category: "Party Wear",
    color: "Grey",
    size: "L",
    price: 1269,
    originalPrice: 1480,
    tag: "Best Seller",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-fashion-dress-gown-elegance_53876-727378.jpg",
  },
  {
    title: "Women Palazzo Set",
    category: "Casual Wear",
    color: "Beige",
    size: "S",
    price: 1404,
    originalPrice: 1726,
    tag: "Popular",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-fashion-dress-gown-elegance_53876-727378.jpg",
  },
  {
    title: "Women Floral Dress",
    category: "Fusion Wear",
    color: "Grey",
    size: "S",
    price: 1415,
    originalPrice: 1713,
    tag: "Trending",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-floral-blue-summer-dress_53876-831765.jpg",
  },
  {
    title: "Women Wrap Dress",
    category: "Party Wear",
    color: "Teal",
    size: "L",
    price: 1472,
    originalPrice: 1870,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-green-striped-summer-dress_53876-829122.jpg",
  },
  {
    title: "Women Linen Dress",
    category: "Fusion Wear",
    color: "White",
    size: "XXL",
    price: 1400,
    originalPrice: 1716,
    tag: "Limited Edition",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-green-wrap-dress_53876-828927.jpg",
  },
  {
    title: "Women Tunic Top",
    category: "Loungewear",
    color: "Navy",
    size: "S",
    price: 1092,
    originalPrice: 1362,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-womens-minimal-long-dress-mockup_53876-1046092.jpg?uid=R155413258&ga=GA1.1.471318040.1721215360&semt=ais_items_boosted&w=740",
  },
  {
    title: "Women Kurti Set",
    category: "Fusion Wear",
    color: "Yellow",
    size: "XL",
    price: 1486,
    originalPrice: 1754,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-green-wrap-dress_53876-828927.jpg",
  },
  {
    title: "Women Tunic Top",
    category: "Fusion Wear",
    color: "Orange",
    size: "XL",
    price: 1377,
    originalPrice: 1764,
    tag: "Limited Edition",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-long-casual-maxi-dress_53876-834127.jpg",
  },
  {
    title: "Women Bodycon Dress",
    category: "Formal Wear",
    color: "Black",
    size: "L",
    price: 1467,
    originalPrice: 1768,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-elegant-yellow-ruffled-dress_53876-829486.jpg",
  },
  {
    title: "Women Linen Dress",
    category: "Casual Wear",
    color: "Black",
    size: "XL",
    price: 1347,
    originalPrice: 1556,
    tag: "Trending",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-green-striped-summer-dress_53876-829122.jpg",
  },
  {
    title: "Women Floral Dress",
    category: "Occasion Wear",
    color: "White",
    size: "XS",
    price: 957,
    originalPrice: 1211,
    tag: "Best Seller",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-green-striped-summer-dress_53876-829122.jpg",
  },
  {
    title: "Women Long Cotton Gown",
    category: "Active Wear",
    color: "Blue",
    size: "S",
    price: 1375,
    originalPrice: 1716,
    tag: "Best Seller",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-green-striped-summer-dress_53876-829122.jpg",
  },
  {
    title: "Women Cotton Midi Dress",
    category: "Party Wear",
    color: "Teal",
    size: "L",
    price: 1003,
    originalPrice: 1329,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-floral-blue-summer-dress_53876-831765.jpg",
  },
  {
    title: "Women Floral Dress",
    category: "Ethnic Wear",
    color: "Beige",
    size: "S",
    price: 1451,
    originalPrice: 1806,
    tag: "New",
    link: "product",
    image:
      "https://img.freepik.com/premium-photo/png-green-striped-summer-dress_53876-829122.jpg",
  },
];
